import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Outlet, Link } from 'react-router-dom';
import { ShoppingCart } from 'lucide-react';
import { Button } from './ui/button';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
export function Layout() {
    const { data: cart } = useQuery({
        queryKey: ['cart'],
        queryFn: () => api.getCart(),
    });
    return (_jsxs("div", { className: "min-h-screen flex flex-col", children: [_jsx("header", { className: "border-b", children: _jsx("div", { className: "container mx-auto px-4 py-4", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsx(Link, { to: "/", className: "text-2xl font-bold", children: "Ecommerce Store" }), _jsxs("nav", { className: "hidden md:flex items-center gap-6", children: [_jsx(Link, { to: "/", className: "text-sm font-medium hover:text-primary", children: "Home" }), _jsx(Link, { to: "/products", className: "text-sm font-medium hover:text-primary", children: "Products" })] }), _jsx("div", { className: "flex items-center gap-4", children: _jsx(Link, { to: "/cart", children: _jsxs(Button, { variant: "outline", size: "icon", className: "relative", children: [_jsx(ShoppingCart, { className: "h-5 w-5" }), cart && cart.itemCount > 0 && (_jsx("span", { className: "absolute -top-2 -right-2 bg-primary text-primary-foreground rounded-full w-5 h-5 text-xs flex items-center justify-center", children: cart.itemCount }))] }) }) })] }) }) }), _jsx("main", { className: "flex-1", children: _jsx(Outlet, {}) }), _jsx("footer", { className: "border-t mt-auto", children: _jsxs("div", { className: "container mx-auto px-4 py-8", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-8", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-4", children: "About" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "Your one-stop shop for custom products with AI-powered designs." })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-4", children: "Links" }), _jsxs("ul", { className: "space-y-2 text-sm", children: [_jsx("li", { children: _jsx(Link, { to: "/products", className: "text-muted-foreground hover:text-foreground", children: "Products" }) }), _jsx("li", { children: _jsx(Link, { to: "/cart", className: "text-muted-foreground hover:text-foreground", children: "Cart" }) })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-semibold mb-4", children: "Contact" }), _jsx("p", { className: "text-sm text-muted-foreground", children: "support@example.com" })] })] }), _jsx("div", { className: "mt-8 pt-8 border-t text-center text-sm text-muted-foreground", children: "\u00A9 2024 Ecommerce Store. All rights reserved." })] }) })] }));
}
