import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { adminApi } from '@/lib/api';
import { Card, CardContent, Button } from '@ecom/ui';
import { formatPrice } from '@/lib/utils';
import { Plus, Edit, Trash2 } from 'lucide-react';
import { ProductCardSkeleton } from '@/components/ProductCardSkeleton';
export function ProductsPage() {
    const { data, isLoading } = useQuery({
        queryKey: ['products'],
        queryFn: () => adminApi.getProducts(),
    });
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-4xl font-bold mb-2", children: "Products" }), _jsx("p", { className: "text-muted-foreground", children: "Manage your product catalog" })] }), _jsxs(Button, { children: [_jsx(Plus, { className: "mr-2 h-4 w-4" }), "Add Product"] })] }), isLoading && (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: Array.from({ length: 6 }).map((_, i) => (_jsx(ProductCardSkeleton, {}, i))) })), data && (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: data.products.map((product) => (_jsx(Card, { children: _jsxs(CardContent, { className: "p-0", children: [_jsx("div", { className: "aspect-square bg-muted", children: product.images[0] ? (_jsx("img", { src: product.images[0], alt: `${product.name} - ${product.description || 'Product image'}`, className: "w-full h-full object-cover", loading: "lazy" })) : (_jsxs("div", { className: "w-full h-full flex items-center justify-center text-muted-foreground", children: [_jsxs("span", { className: "sr-only", children: ["No product image available for ", product.name] }), _jsx("span", { "aria-hidden": "true", children: "No image" })] })) }), _jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "font-semibold mb-1", children: product.name }), _jsx("p", { className: "text-sm text-muted-foreground mb-3 line-clamp-2", children: product.description || 'No description' }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-lg font-bold", children: formatPrice(product.price) }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { size: "icon", variant: "outline", "aria-label": `Edit ${product.name}`, disabled: true, title: "Coming in Phase 2", children: _jsx(Edit, { className: "h-4 w-4" }) }), _jsx(Button, { size: "icon", variant: "outline", "aria-label": `Delete ${product.name}`, disabled: true, title: "Coming in Phase 2", children: _jsx(Trash2, { className: "h-4 w-4" }) })] })] })] })] }) }, product.id))) })), data?.products?.length === 0 && (_jsx("div", { className: "text-center py-12", children: _jsx("p", { className: "text-muted-foreground", children: "No products yet. Add your first product to get started." }) }))] }));
}
